const currencies = [
  {
    blockchainUrl: "https://www.blockchain.com/explorer/transactions/btc/",
    currency: "BTC",
    minDeposit: 0.0001,
    name: "BTC",
    network: "Bitcoin",
    providerId: 0,
  },
  {
    blockchainUrl: "https://www.blockchain.com/explorer/transactions/eth/",
    currency: "ETH",
    minDeposit: 0.005,
    name: "ETH",
    network: "Ethereum",
    providerId: 0,
  },
  {
    blockchainUrl: "https://www.blockchain.com/explorer/transactions/eth/",
    currency: "USDT",
    minDeposit: 5,
    name: "USDT (ETH)",
    network: "Ethereum",
    providerId: 0,
  },
  {
    blockchainUrl: "https://www.blockchain.com/explorer/transactions/eth/",
    currency: "USDC",
    minDeposit: 5,
    name: "USDC (ETH)",
    network: "Ethereum",
    providerId: 0,
  },
  {
    blockchainUrl: "https://tronscan.org/#/transaction/",
    currency: "tUSDT",
    minDeposit: 5,
    name: "USDT (TRX)",
    network: "Tron",
    providerId: 0,
  },
  {
    blockchainUrl: "https://tronscan.org/#/transaction/",
    currency: "tUSDC",
    minDeposit: 5,
    name: "USDC (TRX)",
    network: "Tron",
    providerId: 0,
  },
  {
    currency: "JPY",
    maxDeposit: 300_000,
    minDeposit: 1000,
    name: "JPY",
    nameLong: "Japanese Yen",
    network: "P2P",
    providerId: 1,
  },
  {
    currency: "INR",
    maxDeposit: 200_000,
    minDeposit: 1000,
    name: "INR",
    nameLong: "Indian Rupee",
    network: "P2P",
    providerId: 1,
  },
  {
    currency: "KES",
    minDeposit: 1000,
    name: "KES",
    nameLong: "Kenyan Shilling",
    network: "P2P",
    providerId: 1,
  },
  {
    currency: "UZS",
    minDeposit: 25_000,
    name: "UZS",
    nameLong: "Uzbekistani Som",
    network: "P2P",
    providerId: 1,
  },
  {
    currency: "BDT",
    maxDeposit: 25_000,
    minDeposit: 300,
    name: "BDT",
    nameLong: "Bangladeshi taka",
    network: "P2P",
    providerId: 1,
  },
];

module.exports = currencies;
