name: Build

on:
  workflow_run:
    workflows: [Check Dev, Release]
    types: [completed]

env:
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  IMAGE_PATH: ghcr.io/${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: dockerfile
          tags: ${{ env.IMAGE_PATH }}:${{ env.VERSION }},${{ env.IMAGE_PATH }}:latest

      - name: Send success notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dockerhub
          SLACK_COLOR: "#22c55e"
          SLACK_TITLE: Build Result
          SLACK_MESSAGE: |
            All good! The new `${{ github.repository }}` image has been published.
            ${{ env.IMAGE_PATH }}:${{ env.VERSION }}
          SLACK_FOOTER: ${{ env.ACTION_RUN_URL }}
          SLACK_WEBHOOK: ${{ secrets.DOCKER_SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url,commit

      - name: Send failure notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dockerhub
          SLACK_COLOR: "#ef4444"
          SLACK_TITLE: Build Result
          SLACK_MESSAGE: |
            Oh, bloody hell! The build workflow of the `${{ github.repository }}` image has failed.
          SLACK_FOOTER: ${{ env.ACTION_RUN_URL }}
          SLACK_WEBHOOK: ${{ secrets.DOCKER_SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url,commit
