name: Deployment

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  version-check:
    name: version format check
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check format
        run: |
          VERSION=$(git describe --tags)
          VERSION_FORMAT='^v[0-9]+\.[0-9]+\.[0-9]+$'  # Regular expression for semantic versioning
          if ! [[ "$VERSION" =~ $VERSION_FORMAT ]]; then
            echo "Version $VERSION does not match the required format for a production release (vX.Y.Z). Exiting."
            exit 1
          fi

  deployment:
    needs: [version-check]
    secrets: inherit
    uses: ./.github/workflows/_deployment.yml
    with:
      environment: production
